//user reducer
export const LOADING_USER = "LOADING_USER";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const SET_USER_ERROR = "SET_USER_ERROR";
export const SET_USER = "SET_USER";
export const SET_CART = "SET_CART";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const LOGOUT_USER = "LOGOUT_USER";
export const CLEAR_USER_ERROR = "CLEAR_USER_ERROR";
export const LOADING_USER_UI = "LOADING_USER_UI";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAIL = "ADD_CART_FAIL";
export const SET_ORDERS = "SET_ORDERS";
export const RESET_PASS_SUCCESS = "SET_PASS_SUCCESS";
export const ADD_NEW_PASS_SUCCESS = "ADD_NEW_PASS_SUCCESS";
export const SET_PAYTM_PARAMS = "SET_PAYTM_PARAMS";
export const PAYTM_ERROR = "PAYTM_ERROR";
export const CHANGE_PAYMENT_SUCCESS = "CHANGE_PAYMENT_SUCCESS";
export const RESET_USER_PASS_SUCCESS = "RESET_USER_PASS_SUCCESS";
export const RESET_USER_PASS_ERROR = "RESET_USER_PASS_ERROR";

//seller reducer
export const LOADING_SELLER = "LOADING_SELLER";
export const SELLER_SIGNUP_SUCCESS = "SELLER_SIGNUP_SUCCESS";
export const SET_SELLER_ERROR = "SET_SELLER_ERROR";
export const CLEAR_SELLER_ERROR = "CLEAR_SELLER_ERROR";
export const LOADING_SELLER_UI = "LOADING_SELLER_UI";
export const SET_RESTAURANTS = "SET_RESTAURANTS";
export const SET_RESTAURANT = "SET_RESTAURANT";
export const SET_RESTAURANT_USER = "SET_RESTAURANT_USER";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const EDIT_ITEM = "EDIT_ITEM";
export const LOGOUT_SELLER = "LOGOUT_SELLER";
export const RESET_SELLER_PASS_SUCCESS = "RESET_SELLER_PASS_SUCCESS";
export const RESET_SELLER_PASS_ERROR = "RESET_SELLER_PASS_ERROR";
export const DELETE_SELLER_REST = "DELETE_SELLER_REST";

//admin reducer
export const SET_ADMIN = "SET_ADMIN";
export const DELETE_REST_SUCCESS = "DELETE_REST_SUCCESS";
export const DELETE_REST_FAIL = "DELETE_REST_FAIL";
export const CLEAR_ADMIN_ERROR = "CLEAR_ADMIN_ERROR";
export const SET_ADMIN_ERROR = "SET_ADMIN_ERROR";
export const SET_ALL_RESTAURANTS = "SET_ALL_RESTAURANTS";
export const LOADING_ADMIN_UI = "LOADING_ADMIN_UI";
export const LOGOUT_ADMIN = "LOGOUT_ADMIN";
